version: '3.9'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: kinso
      MYSQL_DATABASE: goku
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:5500"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: kinso
      MYSQL_DATABASE: goku
    volumes:
      - .:/app

volumes:
  db_data:
